---
# Slurm config bwuni gpu
name: "SLURM"   # MUST BE "SLURM"
partition: "gpu"  # "single" for cpu, "gpu_4" or gpu_8" for gpu
job-name: "mnist" # this will be the experiment's name in slurm
num_parallel_jobs: 5  # max number of jobs executed in parallel
ntasks: 1   #  leave that like it is
cpus-per-task: 2   # there are 10 cores for each GPU
mem-per-cpu: 10000  # in MB
time: 1000   # in minutes
sbatch_args: # gpus need to be explicitly requested using this
  gres=gpu:1: ""   #and this
#  nodelist: "node5"

---
name: &name "mnist_gen_train"

# Required: Can also be set in DEFAULT
#path: /tmp/result/mix_digits   # path for saving the results
path: /home/temp_store/andrew_delay/cluster
repetitions: 1    # number of repeated runs for each parameter combination

# Required for AbstractIterativeExperiments only. Can also be set in DEFAULT
iterations: 5000  # number of iterations per repetition.

# Optional: Can also be set in DEFAULT
# Only change these values if you are sure you know what you are doing.
reps_per_job: 1    # number of repetitions in each job. useful for paralellization. defaults to 1.
reps_in_parallel: 1

wandb:
  project: *name
  group: training
  entity: gelikit
  log_interval:  &interval 20
  log_model: true
  model_name: test_model_name

params:
  dim_lat: &dim_lat 128
  act_func: &act_func leaky_relu
  lr: 2e-4
  wd: 5e-5
  vali_log_interval: *interval
  save_model_interval: 200
  seed: 1234
  runtime_noise: true

  results_dir: /home/temp_store/andrew_delay/spn_experiments
  dataset_dir: /home/temp_store/andrew_delay/spn_experiments/data
  device: 'cuda'
  batch_size: 256
  learning_rate: 1e-3
  epochs: 1e5
  model_path: None
  run_name: 'test_run'
  proj_name: 'test_proj'
  eval_interval: 10
  save_interval: 10
  no_wandb: False
  ratspn: False
  RATSPN_R: 3
  RATSPN_D: 3
  RATSPN_I: 3
  RATSPN_S: 3
  RATSPN_dropout: 0.0
  CSPN_sum_param_layers: None
  CSPN_dist_param_layers: None
  CSPN_feat_layers: None
  no_tanh: False
  no_correction_term: False
  sigmoid_std: False
  verbose: False
  sample_onehot: False
  invert: 0.0
  no_eval_at_start: False
  ent_approx: False
  ent_approx__sample_size: 5
  ent_loss_coef: 0.0
  learn_by_sampling: False
  learn_by_sampling__sample_size: 5
